apiVersion: v1
kind: ConfigMap
metadata:
  name: nextcloud-config
  labels:
    app: {{ .Release.Name }}-nextcloud
data:
  my.config.php: |
    <?php
    $CONFIG = array (
      'trusted_domains' =>
         array (
         0 => '*',
      ),
      'datadirectory' => '/var/www/html/nextcloud/data',
      'dbtype' => '{{ .Values.database.type }}',
      'dbname' => '{{ .Values.database.name }}',
      'dbhost' => '{{ .Values.database.host }}',
      'dbport' => '{{ .Values.database.port }}',
      'dbuser' => '{{ .Values.database.user }}',
      'dbpassword' => '{{ .Values.database.password }}',
      'memcache.local' => '\\OC\\Memcache\\APCu',
      'memcache.distributed' => '\\OC\\Memcache\\Redis',
      'memcache.locking' => '\\OC\\Memcache\\Redis',
      'redis' =>
      array (
        'host' => '{{ .Values.redis.host }}',
        'port' => '{{ .Values.redis.port }}',
        'timeout' => '{{ .Values.redis.timeout }}',
        'dbindex' => '{{ .Values.redis.dbindex }}',
      ),
      'objectstore' =>
      array (
        'class' => '\\OC\\Files\\ObjectStore\\S3',
        'arguments' =>
        array (
          'bucket' => '{{ .Values.s3.bucket }}',
          'region' => '{{ .Values.s3.region }}',
        ),
      ),
    );
