apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.replicaCount }}
  strategy:
    canary:
      steps:
        - setWeight: {{ .Values.canarySteps.step1.setWeight }}
        - pause: 
            duration: {{ .Values.canarySteps.step1.pauseDuration }}
        - setWeight: {{ .Values.canarySteps.step2.setWeight }}
        - pause: 
            duration: {{ .Values.canarySteps.step2.pauseDuration }}
        - setWeight: {{ .Values.canarySteps.step3.setWeight }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
    spec:
      containers:
      - name: nextcloud
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        ports:
        - containerPort: 80
        env:
        # Database variables
        - name: NEXTCLOUD_DB_TYPE
          value: "{{ .Values.database.type }}"
        - name: NEXTCLOUD_DB_NAME
          value: "{{ .Values.database.name }}"
        - name: NEXTCLOUD_DB_HOST
          value: "{{ .Values.database.host }}"
        - name: NEXTCLOUD_DB_PORT
          value: "{{ .Values.database.port }}"
        - name: NEXTCLOUD_DB_USER
          value: "{{ .Values.database.user }}"
        - name: NEXTCLOUD_DB_PASSWORD
          value: "{{ .Values.database.password }}"
        # Admin variables
        - name: NEXTCLOUD_ADMIN_USER
          value: "{{ .Values.admin.user }}"
        - name: NEXTCLOUD_ADMIN_PASSWORD
          value: "{{ .Values.admin.password }}"
        - name: NEXTCLOUD_ADMIN_EMAIL
          value: "{{ .Values.admin.email }}"
        # Redis configuration
        - name: NEXTCLOUD_REDIS_HOST
          value: "{{ .Values.redis.host }}"
        - name: NEXTCLOUD_REDIS_PORT
          value: "{{ .Values.redis.port }}"
        - name: NEXTCLOUD_REDIS_TIMEOUT
          value: "{{ .Values.redis.timeout }}"
        - name: NEXTCLOUD_REDIS_DBINDEX
          value: "{{ .Values.redis.dbindex }}"
        # S3 bucket configuration
        - name: NEXTCLOUD_S3_BUCKET
          value: "{{ .Values.s3.bucket }}"
        - name: NEXTCLOUD_S3_REGION
          value: "{{ .Values.s3.region }}"
        volumeMounts:
        - name: config-volume
          mountPath: /var/www/html/nextcloud/config/my.config.php
          subPath: my.config.php
          readOnly: true
        command: 
          - "/bin/bash"
          - "-c"
          - |
              php occ maintenance:install \
              --admin-user=$NEXTCLOUD_ADMIN_USER \
              --admin-pass=$NEXTCLOUD_ADMIN_PASSWORD \
              --admin-email=$NEXTCLOUD_ADMIN_EMAIL \
              --database=$NEXTCLOUD_DB_TYPE \
              --database-name=$NEXTCLOUD_DB_NAME \
              --database-host=$NEXTCLOUD_DB_HOST \
              --database-port=$NEXTCLOUD_DB_PORT \
              --database-user=$NEXTCLOUD_DB_USER \
              --database-pass=$NEXTCLOUD_DB_PASSWORD; \
              sed -i "/);/i \  'installed' => true," config/config.php; \
              php occ db:add-missing-indices; \
              php occ maintenance:repair; \
              sudo supervisord -c /etc/supervisord.conf
      volumes:
      - name: config-volume
        configMap:
          name: nextcloud-config

