apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-nextcloud-ingress
  annotations:
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": {{ .Values.ingress.port }} }]'
    alb.ingress.kubernetes.io/scheme: {{ .Values.ingress.scheme }}
    alb.ingress.kubernetes.io/target-type: instance
spec:
  ingressClassName: alb
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ .Release.Name }}-nextcloud-service
            port:
              number: 80
