apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-active
  namespace: default
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ .Release.Name }}
    role: active
  ports:
  - port: 80
    targetPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-preview
  namespace: default
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ .Release.Name }}
    role: active
  ports:
  - port:  {{ .Values.service.port }}
    targetPort: 80
