apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .Release.Name }}-rollout
  namespace: {{ .Values.applicationNamespace }}
  annotations:
    argocd-image-updater.argoproj.io/image-list: nextcloud={{ .Values.image.repository }}
    argocd-image-updater.argoproj.io/nextcloud.update-strategy: {{ .Values.image.updateStrategy }}
spec:
  project: {{ .Values.project }}
  source:
    repoURL: {{ .Values.source.repoURL }}
    path: {{ .Values.source.path }}
    targetRevision: {{ .Values.source.targetRevision }}
  destination:
    server: {{ .Values.destination.server }}
    namespace: {{ .Values.namespace }}
  syncPolicy:
    automated:
      prune: {{ .Values.syncPolicy.prune }}
      selfHeal: {{ .Values.syncPolicy.selfHeal }}
