name: CI pipeline with Trivy and Docker image publish

on:
  workflow_dispatch:
    inputs:
      release_version:
        description: 'Release version to use'
        required: true
        default: 'latest'

permissions:
  contents: read

jobs:
  trivy:
    permissions:
      contents: read
      security-events: write
      actions: read
    name: Build, scan with Trivy, and push Docker image
    runs-on: ubuntu-20.04

    steps:
      # Checkout code
      - name: Checkout code
        uses: actions/checkout@v4

      # Set up Docker Buildx for building
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Log in to Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Build Docker image using Buildx
      - name: Build Docker image with Buildx
        id: build_image
        uses: docker/build-push-action@v6
        with:
          context: ./server  # Ensure this is the correct path to your Dockerfile
          push: false  # Build but don't push yet
          tags: |
            docker.io/linas37/nextcloud:${{ github.sha }}
            docker.io/linas37/nextcloud:latest
            docker.io/linas37/nextcloud:${{ github.event.inputs.release_version }}
          platforms: linux/amd64  # Only one platform
          secrets: |
            id=NEW_RELIC_API_KEY_PHP,src=${{ secrets.NEW_RELIC_API_KEY_PHP }}
            id=NEW_RELIC_ACCOUNT_ID_PHP,src=${{ secrets.NEW_RELIC_ACCOUNT_ID_PHP }}

      # Run Trivy to scan the built image
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@0.24.0
        with:
          image-ref: docker.io/linas37/nextcloud:${{ github.sha }}
          format: 'template'
          template: '@/contrib/sarif.tpl'
          output: 'trivy-results.sarif'
          severity: 'CRITICAL,HIGH'

      # Upload Trivy scan results to GitHub Security tab
      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: 'trivy-results.sarif'

      # Check Trivy scan results and conditionally push to registry
      - name: Check Trivy scan results
        id: check_trivy
        run: |
          if grep -q '"ruleId":' trivy-results.sarif; then
            echo "Critical or High vulnerabilities found!"
            exit 1
          else
            echo "No critical or high vulnerabilities found."
          fi

      # Push Docker image to Docker Hub if Trivy check passes
      - name: Push Docker image to Docker Hub
        if: success()  # Only run if previous steps succeeded (Trivy scan passed)
        uses: docker/build-push-action@v6
        with:
          context: ./server  # Ensure this is the correct path to your Dockerfile
          push: true  # Push to Docker Hub
          tags: |
            docker.io/linas37/nextcloud:${{ github.sha }}
            docker.io/linas37/nextcloud:latest
            docker.io/linas37/nextcloud:${{ github.event.inputs.release_version }}
          platforms: linux/amd64  # Only one platform
          labels: ${{ steps.meta.outputs.labels }}

      # Generate artifact attestation
      - name: Generate artifact attestation
        uses: actions/attest-build-provenance@v1
        with:
          subject-name: docker.io/linas37/nextcloud
          subject-digest: ${{ steps.build_image.outputs.digest }}
          push-to-registry: true


