
name: CI/CD pipeline with Trivy and Docker image publish

on:
  workflow_dispatch:
    inputs:
      release_version:
        description: 'Release version to use'
        required: true
        default: 'latest'

permissions:
  contents: read

jobs:

  publish_docker:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
      attestations: write
      id-token: write
    steps:
    - name: Check out the repo
      uses: actions/checkout@v4
      with:
        sparse-checkout: server
          
    - name: Log in to Docker Hub
      uses: docker/login-action@v2 
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@v4
      with:
        images: linas37/nextcloud

    - name: Build and push Docker image
      id: push
      uses: docker/build-push-action@v4
      with:
        context: "{{defaultContext}}:server"  
 #        file: ./Dockerfile      
        push: true
        tags: |
          linas37/nextcloud:${{ github.sha }}
          linas37/nextcloud:latest
          linas37/nextcloud:${{ github.event.inputs.release_version }}
        labels: ${{ steps.meta.outputs.labels }}

    - name: Generate artifact attestation
      uses: actions/attest-build-provenance@v1
      with:
        subject-name: docker.io/linas37/nextcloud
        subject-digest: ${{ steps.push.outputs.digest }}
        push-to-registry: true  
